hostname: ISP-3
ip_routing: true

spanning_tree:
  mode: mstp
loopback_interfaces:
- name: Loopback0
  description: ISP-3_lo0
  shutdown: false
  ip_address: 192.168.0.75/32
ethernet_interfaces:
- name: Ethernet1
  peer: P10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.51.75.2/24
- name: Ethernet2
  peer: P11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.52.75.2/24
- name: Ethernet3
  peer: P21
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.54.75.2/24
- name: Ethernet4
  peer: P20
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.53.75.2/24
- name: Ethernet5
  peer: RR5
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet6
  peer: RR6
  type: routed
  shutdown: true
  mtu: 1500

router_bgp:
  as: 65002
  router_id: 192.168.0.75
  peer_groups:
    - name: REGION1
      remote_as: 65101
    - name: REGION2
      remote_as: 65201
  vrfs:
    - name: default
      neighbors:
        - ip_address: 192.51.75.1
          peer_group: REGION1
        - ip_address: 192.52.75.1
          peer_group: REGION1
        - ip_address: 192.53.75.1
          peer_group: REGION2
        - ip_address: 192.54.75.1
          peer_group: REGION2
  address_family_ipv4:
    networks: 
      - prefix: 192.168.0.75/32