hostname: Leaf22
ip_routing: true
spanning_tree:
  mode: mstp
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
- name: Loopback0
  description: Leaf22_lo0
  shutdown: false
  ip_address: 192.168.0.34/32
ethernet_interfaces:
- name: Ethernet1
  peer: H22
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.22.254/24
  vrf: VRF_A
- name: Ethernet2
  peer: Edge22
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.22.34.2/24
- name: Ethernet3
  peer: Edge21
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.21.34.2/24
router_bgp:
  as: 65222
  router_id: 192.168.0.34
  neighbors:
    - ip_address: 192.22.34.1
      remote_as:  65222
  address_family_ipv4:
    networks: 
      - prefix: 192.168.0.34/32
    redistribute_routes:
      - source_protocol: connected
